import { useCallback } from "react";

export const useFormFieldActions = ({
	activeSection,
	setActiveSection,
	fields,
	insert,
	remove,
	move,
	setValue,
	getValues,
}) => {
	const currentItems = getValues("items") || [];
	const activeItemIndex = activeSection > 0 ? activeSection - 1 : null;
	const activeItem =
		activeItemIndex !== null
			? currentItems[activeItemIndex] || fields[activeItemIndex]
			: null;

	const activeContext =
		activeSection === 0
			? {
					isHeader: true,
					title: getValues("title") || "Untitled form",
					description: getValues("description") || "",
				}
			: activeItem;

	// Insert question immediately below the active section
	const handleAddQuestion = useCallback(() => {
		const targetIndex = activeSection === 0 ? 0 : activeSection;
		insert(targetIndex, {
			type: "question",
			questionTitle: "Untitled Question",
			questionType: "multiplechoice",
			options: ["Option 1"],
		});
		setActiveSection(targetIndex + 1);
	}, [activeSection, insert, setActiveSection]);

	// Insert one or multiple questions generated by Gemini AI sequentially below active section
	const handleInsertAIQuestions = useCallback(
		(questions) => {
			if (!Array.isArray(questions) || questions.length === 0) return;
			const targetIndex = activeSection === 0 ? 0 : activeSection;

			questions.forEach((q, idx) => {
				insert(targetIndex + idx, q);
			});

			setActiveSection(targetIndex + questions.length);
		},
		[activeSection, insert, setActiveSection]
	);

	// Update active question with AI-generated question
	const handleUpdateAIQuestion = useCallback(
		(updatedQuestion) => {
			if (!updatedQuestion || activeItemIndex === null) return;
			setValue(`items.${activeItemIndex}`, updatedQuestion, {
				shouldDirty: true,
			});
		},
		[activeItemIndex, setValue]
	);

	// Update form header with AI-generated title & description
	const handleUpdateAIHeader = useCallback(
		(updatedHeader) => {
			if (!updatedHeader) return;
			if (updatedHeader.title) {
				setValue("title", updatedHeader.title, { shouldDirty: true });
			}
			if (updatedHeader.description !== undefined) {
				setValue("description", updatedHeader.description, {
					shouldDirty: true,
				});
			}
		},
		[setValue]
	);

	// Insert title section immediately below the active section
	const handleAddTitle = useCallback(() => {
		const targetIndex = activeSection === 0 ? 0 : activeSection;
		insert(targetIndex, {
			type: "title",
			questionTitle: "Untitled title",
			description: "Description",
		});
		setActiveSection(targetIndex + 1);
	}, [activeSection, insert, setActiveSection]);

	// Insert standalone image section immediately below the active section
	const handleAddImage = useCallback(() => {
		const targetIndex = activeSection === 0 ? 0 : activeSection;
		insert(targetIndex, {
			type: "image",
			title: "Image title",
			image: "",
			imageAlignment: "center",
		});
		setActiveSection(targetIndex + 1);
	}, [activeSection, insert, setActiveSection]);

	// Duplicate an existing question/title card and insert immediately below it
	const handleDuplicateField = useCallback(
		(index) => {
			const itemsList = getValues("items") || [];
			const sourceItem = itemsList[index] || fields[index];
			if (!sourceItem) return;

			const clonedItem = JSON.parse(JSON.stringify(sourceItem));
			delete clonedItem._id;
			delete clonedItem.id;

			insert(index + 1, clonedItem);
			setActiveSection(index + 2);
		},
		[getValues, fields, insert, setActiveSection]
	);

	const handleDeleteField = useCallback(
		(index) => {
			remove(index);
		},
		[remove]
	);

	const handleMoveField = useCallback(
		(fromIndex, toIndex) => {
			if (fromIndex === toIndex) return;
			move(fromIndex, toIndex);
			setActiveSection(toIndex + 1);
		},
		[move, setActiveSection]
	);

	return {
		activeContext,
		handleAddQuestion,
		handleInsertAIQuestions,
		handleUpdateAIQuestion,
		handleUpdateAIHeader,
		handleAddTitle,
		handleAddImage,
		handleDuplicateField,
		handleDeleteField,
		handleMoveField,
	};
};

export default useFormFieldActions;
